# -*- coding: utf-8 -*-
"""ExamenAwa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KU4yQr4hyLOqTkDAXeIDx5zuML6RMWGr

**Fonction polynomiale**
"""

# a.Implementation de la fonction polynomiale
def polynome(x):
  y= x**3-1.5*x**2-6*x + 5
  return y

polynome(5)

