# -*- coding: utf-8 -*-
"""Fibonacci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QK3HH6svlIfMYa4fbcrU37yreNS0uBS5

**fibonacci**
"""

n=int(input("Entrez un nombre:"))
n1 = 0
n2 = 1

print("\n la suite fibonacci est:")
print(n1,",", n2, end=",")
for i in range(2, n):
  next = n1 + n2
  print(next, end=",")
  n1 = n2
  n2 = next

"""**Gestion des exceptions** """

# Erreurs et gestion des exceptions de chaîne de caractère
def chaine_caractere(a):
   
  if (type(a) == str):
    while (type(a)== str):
      print (" ERREUR! Il est impossible de saisir une chaine de caractére")
    a = int(input('Entrez des valeurs numériques pour a ='))
        
        
  elif (type(a) == complex): 
    while (type(a) == complex) :          
       print (" ERREUR! Il est impossible de saisir un nombre complexe")
    a = int(input('Entrez des valeurs numériques pour a ='))       
  elif (a < 0):    
    while (a<0):
      print (" ERREUR! Il est impossible de saisir un numéro négatif")    
    a = int(input("Entrez  un nombre positif pour a "))
  elif a > 10**30 :  
        print (" ERREUR! Il est impossible de saisir un nombre très grand")        
  while (a > 10**30):
    a = int(input("Entrez  des valeurs entières "))
  else:
    b=1
    for c in range(2,a+1):
      b= b + c
      return b